import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// Gurukul: an evolving documentary of LLM research, generated by a
// Teacher/Student pair of Databricks-served foundation models, with
// per-topic confidence tracking, open-problems capture, and a path
// from study journal to research proposal outline.

const config: Config = {
  title: 'Gurukul',
  tagline: 'A self-evolving documentary of LLM research',
  favicon: 'img/favicon.svg',

  url: process.env.SITE_URL ?? 'https://your-username.github.io',
  baseUrl: process.env.SITE_BASE_URL ?? '/gurukul/',

  organizationName: process.env.GITHUB_ORG ?? 'your-username',
  projectName: process.env.GITHUB_REPO ?? 'gurukul',
  deploymentBranch: 'gh-pages',
  trailingSlash: false,

  onBrokenLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  themes: ['@docusaurus/theme-mermaid'],

  presets: [
    [
      'classic',
      {
        docs: {
          path: 'docs',
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          // Opt-in once you've `git init`ed the repo, since this shells
          // out to `git log` for every doc and breaks without git.
          showLastUpdateTime: process.env.GURUKUL_SHOW_LAST_UPDATE === '1',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    colorMode: {
      defaultMode: 'dark',
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Gurukul',
      logo: {
        alt: 'Gurukul',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'journey',
          position: 'left',
          label: 'Journey',
        },
        {to: '/journey-dashboard', label: 'Dashboard', position: 'left'},
        {to: '/proposal', label: 'Proposal Outline', position: 'left'},
        {
          href: 'https://github.com/your-username/gurukul',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [],
      copyright: `Built with Docusaurus. Content is AI-generated and may contain hallucinations; verify before citing.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'json', 'python'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
