// AUTO-GENERATED by scripts/journey.ts. Do not edit by hand.
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  journey: [
    'intro',
  ],
};

export default sidebars;
