import React, {useEffect, useState} from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import {readAll, clearAll} from '@site/src/lib/storage';
// `_topics.json` is regenerated by the journey CLI on every run. It's a
// flat array; the dashboard joins it with localStorage values. A
// default empty graph is committed so this import never fails on a
// fresh checkout.
import topicsData from '@site/docs/_topics.json';

const topicsJson: Array<{
  id: string;
  title: string;
  path: string;
  protocol?: string;
  generatedAt?: string;
}> = (topicsData as {topics?: typeof topicsJson}).topics ?? [];

type LocalState = {
  confidence: Record<string, number>;
  starredProblems: Record<string, Record<string, boolean>>;
  refsStatus: Record<string, Record<string, string>>;
  critiques: Record<string, string>;
  seeds: Record<string, Array<{id: string; text: string}>>;
};

function parseLocalState(raw: Record<string, unknown>): LocalState {
  const out: LocalState = {
    confidence: {},
    starredProblems: {},
    refsStatus: {},
    critiques: {},
    seeds: {},
  };
  for (const [k, v] of Object.entries(raw)) {
    const m = k.match(/^topic:([^:]+):(.+)$/);
    if (!m) continue;
    const [, topicId, field] = m;
    if (field === 'confidence' && typeof v === 'number') {
      out.confidence[topicId] = v;
    } else if (field === 'openProblems' && v && typeof v === 'object') {
      out.starredProblems[topicId] = v as Record<string, boolean>;
    } else if (field === 'refs' && v && typeof v === 'object') {
      out.refsStatus[topicId] = v as Record<string, string>;
    } else if (field === 'critique' && typeof v === 'string') {
      out.critiques[topicId] = v;
    } else if (field === 'seeds' && Array.isArray(v)) {
      out.seeds[topicId] = v as Array<{id: string; text: string}>;
    }
  }
  return out;
}

function confidenceColor(n: number): string {
  if (n >= 4) return 'gk-confidence-high';
  if (n >= 2) return 'gk-confidence-med';
  if (n >= 1) return 'gk-confidence-low';
  return 'gk-confidence-low';
}

export default function JourneyDashboard() {
  const [state, setState] = useState<LocalState | null>(null);

  useEffect(() => {
    setState(parseLocalState(readAll()));
    const refresh = () => setState(parseLocalState(readAll()));
    window.addEventListener('gurukul:storage', refresh);
    return () => window.removeEventListener('gurukul:storage', refresh);
  }, []);

  const totalSeeds = state
    ? Object.values(state.seeds).reduce((a, b) => a + b.length, 0)
    : 0;
  const totalStarred = state
    ? Object.values(state.starredProblems).reduce(
        (a, b) => a + Object.values(b).filter(Boolean).length,
        0,
      )
    : 0;
  const refsCounts = (() => {
    if (!state) return {verified: 0, wrong: 0, missing: 0, unverified: 0};
    const c = {verified: 0, wrong: 0, missing: 0, unverified: 0};
    for (const m of Object.values(state.refsStatus)) {
      for (const s of Object.values(m)) {
        if (s in c) c[s as keyof typeof c] += 1;
      }
    }
    return c;
  })();

  return (
    <Layout
      title="Journey Dashboard"
      description="Your evolving map of LLM research"
    >
      <main className="container margin-vert--lg">
        <h1>Your journey, so far</h1>
        <p style={{color: 'var(--gk-muted)'}}>
          Aggregated from your locally-saved confidence ratings, starred
          open problems, reference verifications, and research seeds.
          Nothing here leaves your browser.
        </p>

        <div className="gk-grid">
          <Stat label="Topics in journey" value={topicsJson.length} />
          <Stat
            label="Topics rated"
            value={state ? Object.keys(state.confidence).length : 0}
          />
          <Stat label="Starred open problems" value={totalStarred} />
          <Stat label="Research seeds" value={totalSeeds} />
          <Stat
            label="Refs verified"
            value={`${refsCounts.verified} / ${
              refsCounts.verified +
              refsCounts.wrong +
              refsCounts.missing +
              refsCounts.unverified
            }`}
          />
        </div>

        <h2 style={{marginTop: '2rem'}}>Topics</h2>
        {topicsJson.length === 0 ? (
          <EmptyState />
        ) : (
          <table className="gk-table">
            <thead>
              <tr>
                <th>Topic</th>
                <th>Protocol</th>
                <th>Confidence</th>
                <th>Pushback?</th>
                <th>Seeds</th>
                <th>★ problems</th>
              </tr>
            </thead>
            <tbody>
              {topicsJson.map((t) => {
                const conf = state?.confidence[t.id] ?? 0;
                const hasCritique = !!state?.critiques[t.id]?.trim();
                const seeds = state?.seeds[t.id]?.length ?? 0;
                const starred = state
                  ? Object.values(state.starredProblems[t.id] ?? {}).filter(
                      Boolean,
                    ).length
                  : 0;
                return (
                  <tr key={t.id}>
                    <td>
                      <Link to={t.path}>{t.title}</Link>
                    </td>
                    <td>{t.protocol ?? '—'}</td>
                    <td className={confidenceColor(conf)}>
                      {conf === 0 ? '—' : '★'.repeat(conf)}
                    </td>
                    <td>{hasCritique ? 'yes' : '—'}</td>
                    <td>{seeds || '—'}</td>
                    <td>{starred || '—'}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        )}

        <h2 style={{marginTop: '2rem'}}>Aggregated research seeds</h2>
        {state && totalSeeds > 0 ? (
          <ul>
            {Object.entries(state.seeds).flatMap(([topicId, seeds]) =>
              seeds.map((s) => (
                <li key={s.id}>
                  <strong>{topicId}:</strong> {s.text}
                </li>
              )),
            )}
          </ul>
        ) : (
          <p style={{color: 'var(--gk-muted)'}}>
            No seeds yet. Capture them inline as you read each topic.
          </p>
        )}

        <h2 style={{marginTop: '2rem'}}>Where you pushed back</h2>
        {state && Object.values(state.critiques).some((s) => s?.trim()) ? (
          <ul>
            {Object.entries(state.critiques)
              .filter(([, v]) => v?.trim())
              .map(([topicId, v]) => (
                <li key={topicId} style={{marginBottom: '0.6rem'}}>
                  <strong>{topicId}:</strong> {v}
                </li>
              ))}
          </ul>
        ) : (
          <p style={{color: 'var(--gk-muted)'}}>
            No pushback recorded yet. Disagreements are where novel ideas
            live — try to write at least one per topic.
          </p>
        )}

        <div style={{marginTop: '2rem'}}>
          <Link to="/proposal" className="gk-button">
            → Draft a research proposal outline from this journey
          </Link>
          <button
            type="button"
            className="gk-button"
            style={{marginLeft: '0.6rem'}}
            onClick={() => {
              if (
                confirm(
                  'Wipe all local progress (confidence, seeds, critiques, refs)?',
                )
              ) {
                clearAll();
              }
            }}
          >
            Reset all local progress
          </button>
        </div>
      </main>
    </Layout>
  );
}

function Stat({label, value}: {label: string; value: React.ReactNode}) {
  return (
    <div className="gk-card">
      <div className="gk-card__label">{label}</div>
      <div style={{fontSize: '1.6rem', fontWeight: 700}}>{value}</div>
    </div>
  );
}

function EmptyState() {
  return (
    <div className="gk-card">
      <p>
        No topics generated yet. From the project root, run{' '}
        <code>npm run journey</code> to generate your first topic.
      </p>
    </div>
  );
}
