// Interactive CLI for generating a topic and weaving it into the journey.
//
// Flow:
//   1. Read docs/_topics.json to know what's been covered.
//   2. Optionally ask the Teacher for next-topic suggestions.
//   3. Prompt user to confirm/edit the topic and pick a protocol.
//   4. Run the protocol -> validated TopicPayload.
//   5. Render MDX -> write to docs/.
//   6. Update _topics.json and regenerate sidebars.generated.ts.

import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import prompts from 'prompts';
import {
  loadConfig,
  assertConfigured,
  call,
  extractJson,
} from './fm-client.js';
import {runProtocol, type ProtocolName} from './protocols.js';
import {renderMdx} from './mdx-render.js';
import {
  JourneyGraphSchema,
  type JourneyGraph,
  type TopicEntry,
} from './schema.js';
import {TEACHER_SYSTEM} from './prompts.js';

const ROOT = path.resolve(process.cwd());
const DOCS_DIR = path.join(ROOT, 'docs');
const TOPICS_FILE = path.join(DOCS_DIR, '_topics.json');
const SIDEBAR_FILE = path.join(ROOT, 'sidebars.generated.ts');

const PROTOCOLS: Array<{value: ProtocolName; title: string}> = [
  {
    value: 'outline-write-critique',
    title: 'outline-write-critique (default; richest)',
  },
  {value: 'socratic', title: 'socratic (Q&A style)'},
  {value: 'debate', title: 'debate (pro vs con synthesis)'},
];

function readGraph(): JourneyGraph {
  if (!fs.existsSync(TOPICS_FILE)) return {topics: []};
  try {
    const raw = JSON.parse(fs.readFileSync(TOPICS_FILE, 'utf8'));
    return JourneyGraphSchema.parse(raw);
  } catch (err) {
    console.warn(
      `Warning: ${TOPICS_FILE} is malformed (${(err as Error).message}). Starting from empty.`,
    );
    return {topics: []};
  }
}

function writeGraph(g: JourneyGraph): void {
  fs.mkdirSync(DOCS_DIR, {recursive: true});
  fs.writeFileSync(TOPICS_FILE, JSON.stringify(g, null, 2) + '\n', 'utf8');
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80);
}

function safeFsName(s: string): string {
  return slugify(s) || `topic-${Date.now()}`;
}

async function suggestNext(
  graph: JourneyGraph,
): Promise<{title: string; isComparison: boolean; rationale: string}[]> {
  const cfg = loadConfig();
  if (cfg.dryRun) {
    return [
      {
        title: 'Foundations of language modeling',
        isComparison: false,
        rationale: '[stub] start at the beginning',
      },
      {
        title: 'Transformer architecture: attention is all you need',
        isComparison: false,
        rationale: '[stub] the building block',
      },
      {
        title:
          'Frontier model comparison: GPT, Claude, Kimi, Qwen, DeepSeek',
        isComparison: true,
        rationale: '[stub] the payoff chapter',
      },
    ];
  }

  const covered = graph.topics.map((t) => t.title);
  const messages = [
    {role: 'system' as const, content: TEACHER_SYSTEM},
    {
      role: 'user' as const,
      content: `Propose the next 3 topics for an evolving documentary of LLM research aimed at someone who wants to write a research proposal in this area. The journey should build progressively, ending with a frontier-model comparison.\n\nAlready covered (${covered.length}):\n${covered.length ? '- ' + covered.join('\n- ') : '(nothing yet)'}\n\nReturn strict JSON only:\n{ "suggestions": [ { "title": "string", "is_comparison": false, "rationale": "one sentence" } ] }`,
    },
  ];
  const res = await call(cfg, {
    endpoint: 'teacher',
    messages,
    jsonOnly: true,
  });
  const parsed = extractJson(res.text) as {
    suggestions?: Array<{
      title?: string;
      is_comparison?: boolean;
      rationale?: string;
    }>;
  };
  return (parsed.suggestions ?? [])
    .filter((s) => s.title)
    .map((s) => ({
      title: String(s.title),
      isComparison: !!s.is_comparison,
      rationale: String(s.rationale ?? ''),
    }));
}

function regenerateSidebar(graph: JourneyGraph): void {
  const items = graph.topics
    .slice()
    .sort((a, b) => a.position - b.position)
    .map((t) => `    '${t.id}'`)
    .join(',\n');
  const ts = `// AUTO-GENERATED by scripts/journey.ts. Do not edit by hand.
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  journey: [
${items || "    // No topics yet. Run \\`npm run journey\\` to generate one."}
  ],
};

export default sidebars;
`;
  fs.writeFileSync(SIDEBAR_FILE, ts, 'utf8');
}

async function main() {
  console.log('Gurukul · journey generator');
  console.log('---------------------------');

  const cfg = loadConfig();
  try {
    assertConfigured(cfg);
  } catch (e) {
    console.error(`✗ ${(e as Error).message}`);
    process.exit(1);
  }
  if (cfg.dryRun) {
    console.log('Mode: DRY RUN (no Databricks calls; stub responses)');
  } else {
    console.log(
      `Mode: live · teacher=${cfg.teacherEndpoint} · student=${cfg.studentEndpoint}`,
    );
  }

  const graph = readGraph();
  console.log(`Journey size: ${graph.topics.length} topic(s) covered.`);

  // 1. Topic selection
  let topicTitle = '';
  let isComparison = false;
  const {mode} = await prompts({
    type: 'select',
    name: 'mode',
    message: 'How do you want to choose the topic?',
    choices: [
      {title: 'Let the Teacher suggest', value: 'suggest'},
      {title: 'Type my own', value: 'manual'},
    ],
    initial: 0,
  });
  if (!mode) {
    console.log('Cancelled.');
    return;
  }

  if (mode === 'suggest') {
    const suggestions = await suggestNext(graph);
    const {pick} = await prompts({
      type: 'select',
      name: 'pick',
      message: 'Pick a topic',
      choices: [
        ...suggestions.map((s) => ({
          title: `${s.title}  —  ${s.rationale}`,
          value: s,
        })),
        {title: '(type my own instead)', value: null},
      ],
    });
    if (pick) {
      topicTitle = pick.title;
      isComparison = pick.isComparison;
    }
  }

  if (!topicTitle) {
    const {typed} = await prompts({
      type: 'text',
      name: 'typed',
      message: 'Topic title?',
      validate: (s: string) => (s.trim().length >= 4 ? true : 'Too short'),
    });
    if (!typed) {
      console.log('Cancelled.');
      return;
    }
    topicTitle = typed.trim();

    const {cmp} = await prompts({
      type: 'confirm',
      name: 'cmp',
      message: 'Is this a frontier-model comparison chapter?',
      initial: /comparison|gpt.*claude|model.*comparison/i.test(topicTitle),
    });
    isComparison = !!cmp;
  }

  // 2. Protocol
  const {protocol} = (await prompts({
    type: 'select',
    name: 'protocol',
    message: 'Protocol?',
    choices: PROTOCOLS.map((p) => ({title: p.title, value: p.value})),
    initial: 0,
  })) as {protocol: ProtocolName};
  if (!protocol) {
    console.log('Cancelled.');
    return;
  }

  // 3. Generate
  console.log(`\nGenerating "${topicTitle}" with ${protocol}...`);
  const t0 = Date.now();
  const {payload} = await runProtocol(cfg, {
    topicTitle,
    protocol,
    comparison: isComparison,
    priorTopics: graph.topics.map((t) => t.title),
    log: (s) => console.log(`  · ${s}`),
  });
  const elapsed = ((Date.now() - t0) / 1000).toFixed(1);
  console.log(`Done in ${elapsed}s.`);

  // 4. Decide filename + position
  const slug = safeFsName(topicTitle);
  const id = slug;
  const position = graph.topics.length + 1;
  const filePosition = String(position * 10).padStart(3, '0');
  const fname = `${filePosition}-${slug}.mdx`;
  const filePath = path.join(DOCS_DIR, fname);
  const entry: TopicEntry = {
    id,
    title: topicTitle,
    path: `/${slug}`,
    slug,
    protocol,
    teacher: cfg.teacherEndpoint,
    student: cfg.studentEndpoint,
    generatedAt: new Date().toISOString(),
    isComparison,
    parentId: graph.topics[graph.topics.length - 1]?.id ?? null,
    position,
  };

  // 5. Preview + confirm
  const mdx = renderMdx({entry, payload});
  console.log(`\n--- MDX preview (${mdx.length} chars) ---`);
  console.log(mdx.slice(0, 800) + (mdx.length > 800 ? '\n...' : ''));
  console.log(`--- end preview ---\n`);

  const {accept} = await prompts({
    type: 'confirm',
    name: 'accept',
    message: `Write to ${path.relative(ROOT, filePath)} and update sidebar?`,
    initial: true,
  });
  if (!accept) {
    console.log('Discarded.');
    return;
  }

  fs.mkdirSync(DOCS_DIR, {recursive: true});
  fs.writeFileSync(filePath, mdx, 'utf8');

  graph.topics.push(entry);
  writeGraph(graph);
  regenerateSidebar(graph);

  console.log(`\n✓ Wrote ${path.relative(ROOT, filePath)}`);
  console.log(`✓ Updated ${path.relative(ROOT, TOPICS_FILE)}`);
  console.log(`✓ Updated ${path.relative(ROOT, SIDEBAR_FILE)}`);
  console.log(`\nNext: npm start    to preview the journey.`);
}

main().catch((err) => {
  console.error('\n✗ Journey generation failed:');
  console.error(err);
  process.exit(1);
});
